### PR TITLE
making it all more generic

### PR DESCRIPTION
**Pull request by jamesgorrie**
Just adding a usage rights editor and also removing all the very specific stuff.

### CODE REVIEW

**Comment by theefer** [comment]
Looks fine, but what's an example invocation?

**Comment by jamesgorrie** [comment]
Same as metadata:

```
./batcher.js editUsageRights 'by:"Felix Clay"' '{ "free": false }'  '{ "category": "comissioned-photographer", "photographer": "Felix Clay", "publication": "The Guardian" }'
```

or

```
./batcher.js patchMetadata 'by:"Felix Clay"' '{ "free": false }'  '{ "byline": "Felix Clay" }'
```

**Comment by theefer** [comment]
Do you think it's worth slapping these examples in a README? I must admit it's not trivial to reverse engineer from the code imho.

**Comment by theefer** [comment]
:+1:

**Comment by jamesgorrie** [comment]
> I must admit it's not trivial to reverse engineer from the code imho

Currying can do that a bit - there's a massive over abstraction smell here.
I've added the example in the console.

**Pull request merged**
